upgraded script to support reverse tunnels
what does this mean? reverse runneling is a way to
allow us to ssh to a device by ssh'ing to another
device. crazy, huh! the way it works is as follows

port not accessible      port accessible
[firewalled device] <--- [server with public ip]
                    ^ this is the reverse tunnel

in this scenario, the IP we are connecting to via
ssh is NOT necessarily the IP of the device we want
to Mosh into. hence we must go through a public IP
discovery using SSH and ensure to bind the mosh
server to the correct IP address in this case.

diff --git a/mosh-jump b/mosh-jump
--- a/mosh-jump
+++ b/mosh-jump
@@ -99,15 +99,34 @@ if ! install_mosh; then
     exit 1
 fi
 
-# Install mosh on the jump server if needed
-"${ssh_command[@]}" "$REMOTE_JUMP_SSH_HOST" bash <<EOF
+# Install mosh on the jump server if needed, and obtain
+# the external IP address, favouring IPv6 over IPv4
+public_ip="$("${ssh_command[@]}" "$REMOTE_JUMP_SSH_HOST" bash <<EOF
 $(declare -f install_mosh)
-install_mosh
+if ! install_mosh; then exit \$?; fi
+IP=\$(curl -s -6 ifconfig.me)
+if [[ -n "\$IP" ]]; then 
+    echo "\$IP"
+else 
+    IP=\$(curl -s -4 ifconfig.me)
+    if [[ -n "\$IP" ]]; then 
+        echo "\$IP"
+    fi
+fi
+exit 0
 EOF
+)"
 
 if [[ $? -ne 0 ]]; then
     echo "Error: Failed to install mosh on remote" >&2
     exit 1
+fi
+
+if [[ -z "$public_ip" ]]; then 
+    echo "Error: Failed to retrieve public IP on remote" >&2
+    exit 1
+else
+    echo "Mosh will bind to $public_ip on port(s) $REMOTE_JUMP_MOSH_PORTS"
 fi
 
 # Build properly quoted arguments for remote execution
@@ -123,5 +142,9 @@ if [[ -z "$LC_CTYPE" ]]; then
 fi
 
 # Connect via mosh
-exec mosh --ssh="${ssh_command[*]}" -p "$REMOTE_JUMP_MOSH_PORTS" "$REMOTE_JUMP_SSH_HOST" -- bash \
+exec mosh \
+    --ssh="${ssh_command[*]}" \
+    --bind-server="$public_ip" \
+    -p "$REMOTE_JUMP_MOSH_PORTS" \
+    "$REMOTE_JUMP_SSH_HOST" -- bash \
     -c "$(declare -f execute_on_the_remote); execute_on_the_remote ssh$remote_args"
